sudo: false

language: go

go:
  - 1.16.x

env:
  - GO111MODULE=on

script:
  - ./generate.sh
  # TODO: ensure gunk doesn't generate
  # a different filedescriptor each time
  # even when no changes in .gunk
  # - git diff --exit-code
